### ISSUE TITLE
test issue for discord bot

### ISSUE THREAD

**Issue by Daki-Slasher** [roscog/Lumin#1]
test issue description

**Comment by Daki-Slasher** [comment]
test issue comment 1 edit test

**Comment by Daki-Slasher** [comment]
test issue comment 2 with file 
![jurgen](https://github.com/roscog/Lumin/assets/75721813/75c734a8-9338-47f9-a04b-fd3ad0f8bfbe)

**Comment by roscog** [comment]
post here aswell

**Comment by roscog** [comment]
this test-message was send from discord!

**Comment by roscog** [comment]
This is a reply only you can see!

**Comment by roscog** [comment]
This is a reply only you can see!

**Comment by roscog** [comment]
This is a reply only you can see!

**Comment by roscog** [comment]
This is a reply only you can see!

**Comment by roscog** [comment]
reply
